### ISSUE TITLE
Webpack 5.1.3^ and xml-webpack-plugin deprecation warning

### ISSUE THREAD

**Issue by casperfibaek** [rvanmil/xml-webpack-plugin#1]
Running webpack 5 and xml-webpack-plugin produces the following deprecation warning:

(node:13452) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

This thread seems to be discussing the same issue: 
https://github.com/webpack/webpack/issues/11425

**Comment by rvanmil** [comment]
@casperfibaek apologies for the late response, I completely missed this issue. I’ll take a look at this.

**Comment by rvanmil** [comment]
Should be fixed in version 1.2.0 with support for both webpack 4 and 5 😊
